### PR TITLE
chore: change nexus URL

### PR DESCRIPTION
**Pull request by pihme**
Changed URL to point to new Artifactory URL

### CODE REVIEW

**Comment by Langleu** [comment]
@pihme , looks good so far.
I'd suggest adjusting the occurrences here as well: https://github.com/zeebe-io/flaky-test-extractor-maven-plugin/blob/2cb0803bca609aeef7355217991df22c0e9a45d2/pom.xml#L155-L179
Not entirely sure what the block does, but just to be on the safe side.
URL would again be e.g. `https://artifacts.camunda.com/artifactory/zeebe-io-snapshots/`

**Review by Langleu — APPROVED** [review]
thanks!

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors retry

**Comment by Langleu** [comment]
Okay, in that case, it seems to be not the proxy but just Artifactory in general.
Not much we can do atm, will write it down.
Weird that it actually manages to upload everything.

**Pull request merged**
